### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function StarringJane\WordpressBlade\array_flatten() in Hooks.php on line 72

### ISSUE THREAD

**Issue by luanpiegas** [starringjane/wordpress-blade#3]
Full error:

`Fatal error: Uncaught Error: Call to undefined function StarringJane\WordpressBlade\array_flatten() in C:\Users\user\sites\mytheme\app\public\wp-content\themes\my-theme\vendor\starring-jane\wordpress-blade\src\Hooks.php on line 72`

composer.json:
```
{
    "name": "luan/mytheme",
    "type": "project",
    "require": {
        "starring-jane/wordpress-blade": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "MyTheme\\": "wp-content/themes/my-theme"
        }
    },
    "authors": [
        {
            "name": "Luan"
        }
    ]
}
```

**Comment by MaximVanhove** [comment]
Can you try `composer require laravel/helpers` ?

**Comment by luanpiegas** [comment]
it worked, thank you!
