### ISSUE TITLE
Feature Request: Component Namespacing

### ISSUE THREAD

**Issue by craigrileyuk** [starringjane/wordpress-blade#5]
First of all, thanks for the awesome project. We have to work with Wordpress and you've made PHP templating bearable again!

So the place I work at now uses Blade components in our theme which are installed as usual.

But we also have a plugin which contains a few common, unstyled components that we like to use in our themes.

At the moment, we're passing an array of directories to the `WordpressBlade::create` method with the theme views directory being the first array item and the plugin components directory being a second array item.

However, it'd be really useful if we could use [Blade namespacing](https://laravel.com/docs/8.x/blade#manually-registering-components) so we could do something like

```php
// Some boot method
WordpressBlade::componentNamespace('Nightshade\\Views\\Components', 'nightshade');

// Some blade file
<x-nightshade::calendar />
<x-nightshade::color-picker />
```

**Comment by MaximVanhove** [comment]
It looks like a great idea to me. I would accept a PR for this feature.

What plugin do you use?

**Comment by craigrileyuk** [comment]
The plugin is a private one for internal use. But it just registers a few common Blade components.

So I spent an hour or so investigating if my own coding skills could handle this and I came up short.

It seems that the underlying BladeCompiler you're dependent upon isn't new enough to support anonymous components and the ComponentTagCompiler would need to support them too.

It's probably possible to get `componentNamespace` working, but that would only support class-based components and ideally I'd be using `anonymousComponentNamespace` to load a directory of anonymous blade components under a namespace.

Support seems to have been added in [Laravel 9.8](https://laravel-news.com/laravel-9-8-0) but obviously we're a bit behind that now.

In short, it was beyond me :)

**Comment by MaximVanhove** [comment]
I'll take a look to remove the jenssegers/blade dependency and implement it directly. It should allow us to move faster.

**Comment by MaximVanhove** [comment]
Good news everyone! I added support for illuminate/view v9 in [v1.0.12](https://github.com/starringjane/wordpress-blade/releases/tag/1.0.12) and all methods from blade can now be called statically.

This means you can register anonymous blade components with their own namespace:

```php
WordpressBlade::anonymousComponentNamespace('flights.bookings', 'flights');
```
