### ISSUE TITLE
BindingResolutionException when using anonymous components

### ISSUE THREAD

**Issue by craigrileyuk** [starringjane/wordpress-blade#6]
To reproduce:

1. Install  v1.0.12
2. Create a blank theme with the layout and files as instructed (Standard Wordpress)
3. Got the following code in the `functions.php` file

```php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
}


use StarringJane\WordpressBlade\WordpressBlade;

WordpressBlade::create(
    get_theme_file_path('views'), // Path to all blade files
    get_theme_file_path('cache/views'), // Path to blade cache
);
```

I have `/templates/index.php` return the view at `pages.default` which `@extends('layouts.main')` all okay.

Error occurs if I use an anonoymous component, e.g. `<x-test></x-test>` where `/views/components/test.blade.php` is a `<div>` with Hello World in it.

Here's the error output

> Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\View\Factory] is not instantiable. in /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/container/Container.php:1103 Stack trace: #0 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/container/Container.php(898): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...') #1 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Illuminate\\Cont...') #2 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array) #3 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(278): Illuminate\Container\Container->make('Illuminate\\Cont...') #4 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(235): Illuminate\View\Compilers\ComponentTagCompiler->componentClass('test') #5 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(156): Illuminate\View\Compilers\ComponentTagCompiler->componentString('test', Array) #6 [internal function]: Illuminate\View\Compilers\ComponentTagCompiler->Illuminate\View\Compilers\{closure}(Array) #7 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(151): preg_replace_callback('/\n <...', Object(Closure), '@extends('layou...') #8 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(90): Illuminate\View\Compilers\ComponentTagCompiler->compileOpeningTags('@extends('layou...') #9 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/ComponentTagCompiler.php(76): Illuminate\View\Compilers\ComponentTagCompiler->compileTags('@extends('layou...') #10 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/BladeCompiler.php(423): Illuminate\View\Compilers\ComponentTagCompiler->compile('@extends('layou...') #11 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/BladeCompiler.php(255): Illuminate\View\Compilers\BladeCompiler->compileComponentTags('@extends('layou...') #12 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Compilers/BladeCompiler.php(175): Illuminate\View\Compilers\BladeCompiler->compileString('@extends('layou...') #13 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/Engines/CompilerEngine.php(62): Illuminate\View\Compilers\BladeCompiler->compile('/Users/riley/Co...') #14 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/Users/riley/Co...', Array) #15 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents() #16 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents() #17 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/view/View.php(480): Illuminate\View\View->render() #18 /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/starring-jane/wordpress-blade/src/Hooks.php(44): Illuminate\View\View->toHtml() #19 /Users/riley/Code/Valet/new-blade/web/wp/wp-includes/class-wp-hook.php(310): StarringJane\WordpressBlade\Hooks->action_template_include('/Users/riley/Co...') #20 /Users/riley/Code/Valet/new-blade/web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('/Users/riley/Co...', Array) #21 /Users/riley/Code/Valet/new-blade/web/wp/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/Users/riley/Co...') #22 /Users/riley/Code/Valet/new-blade/web/wp/wp-blog-header.php(19): require_once('/Users/riley/Co...') #23 /Users/riley/Code/Valet/new-blade/web/index.php(6): require('/Users/riley/Co...') #24 /Users/riley/.composer/vendor/laravel/valet/server.php(110): require('/Users/riley/Co...') #25 {main} thrown in /Users/riley/Code/Valet/new-blade/web/app/themes/test/vendor/illuminate/container/Container.php on line 1103

**Comment by MaximVanhove** [comment]
Fixed in 1.0.13
